Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_url = "file:///R:/DEV/education/otus/_boxes/bento-ubuntu-24.04.box"
  config.vm.box_check_update = false
  config.ssh.keys_only = false

  config.vm.hostname = "otus-hw07"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "otus-hw07"
  end
end
