# Стенд под KVM/libvirt на рабочей станции ubuntu-otus.
Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.hostname = "otus-hw16"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "libvirt" do |lv|
    lv.cpus = 2
    lv.memory = 2048
    lv.machine_virtual_size = 20
    lv.default_prefix = "otus-hw16_"
  end
end
