# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/9"
  config.vm.box_version = "9.4.20240805"
  # На Windows-хосте нет Ansible: плейбук копируется в гостя и выполняется там (ansible_local)
  config.vm.provision "shell", inline: "rm -rf /tmp/provisioning"
  config.vm.provision "file", source: "provisioning", destination: "/tmp/provisioning"
  config.vm.provision "ansible_local" do |ansible|
    #ansible.verbose = "vvv"
    ansible.provisioning_path = "/tmp/provisioning"
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
    v.cpus = 2
    # Хост без VT-x (VirtualBox через Hyper-V/NEM): UEFI box'а зависает на DXE_AP, образ гибридный и грузится через BIOS
    v.customize ["modifyvm", :id, "--firmware", "bios"]
  end

  config.vm.define "ns01" do |ns01|
    ns01.vm.synced_folder ".", "/vagrant", disabled: true
    ns01.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
    ns01.vm.hostname = "ns01"
  end

  config.vm.define "client" do |client|
    client.vm.synced_folder ".", "/vagrant", disabled: true
    client.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "dns"
    client.vm.hostname = "client"
  end

end
