Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.box_version = "9.3.20231118"
  # Не проверять обновления в сети (для offline-стенда)
  config.vm.box_check_update = false
  # отключаю вход только по ключам
  config.ssh.keys_only = false

  # подготавливаю сервер NFS
  config.vm.hostname = "alma-otus"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
    vb.name = "alma-otus"
  end
end