# Box берётся из _boxes/ в корне репозитория; путь считается от этого файла и переживает перенос репозитория.
BOX_FILE = File.expand_path("../../_boxes/bento-ubuntu-24.04.box", __dir__)

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_url = "file:///#{BOX_FILE}"
  config.vm.box_check_update = false
  config.ssh.keys_only = false

  config.vm.hostname = "otus-hw18"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "2048"
    vb.name = "otus-hw18"
  end
end
